version: '3.8'

services:
    # run redis on port 6379
  cache:
    container_name: cache
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'
    # starts the redis server, saves data to disk every 20 seconds so it can persist between restarts, and
    # sets a password
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass
    # for persisting data to disk
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
